[package]
name = "edupt_rust"
version = "0.1.0"
authors = ["amejii <nanahachiroku786@gmail.com>"]

[dependencies]
vecmath = "0.3.1"

[lib]
name = "edupt"
path = "src/lib.rs"

[[bin]]
name = "executable"
path = "src/main.rs"